#mysql开发环境
dev:
  database: database
  host: mysql.xxx.com
  dialect: mysql
  password: xxx
  username: username
  timezone: +08:00
  pool:
    max: 5
    min: 1
    acquire: 30000
    idle: 10000
#mysql测试环境
test:
  database: database
  host: mysql.xxx.com
  dialect: mysql
  password: xxx
  username: pp_test
  timezone: +08:00
  pool:
    max: 5
    min: 1
    acquire: 30000
    idle: 10000
#mysql生产环境
production:
  database: database
  host: mysql.xxx.com
  dialect: mysql
  password: xxx
  username: pp_test
  timezone: +08:00
  pool:
    max: 5
    min: 1
    acquire: 30000
    idle: 10000
